-- Drop tables in reverse order of dependencies to avoid FK conflicts if re-running
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE tblOrderDetail CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE tblOrder CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE tblCustomer CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE tblBookAuthor CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE tblBook CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE tblAuthor CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Author Table
CREATE TABLE tblAuthor (
    AuthorID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    AuthorName VARCHAR2(100) NOT NULL
);

-- Book Table
CREATE TABLE tblBook (
    BookID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    BookTitle VARCHAR2(200) NOT NULL,
    AuthorID NUMBER,  -- Optional direct FK (denormalized), but not needed if BookAuthor used
    BookPublisher VARCHAR2(100),
    BookPublicationDate DATE,
    BookPrice NUMBER(8,2),
    BookQuantity NUMBER,
    CONSTRAINT fk_book_author FOREIGN KEY (AuthorID) REFERENCES tblAuthor(AuthorID)
);

-- BookAuthor Junction Table
CREATE TABLE tblBookAuthor (
    BookAuthorID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    BookID NUMBER NOT NULL,
    AuthorID NUMBER NOT NULL,
    CONSTRAINT fk_ba_book FOREIGN KEY (BookID) REFERENCES tblBook(BookID),
    CONSTRAINT fk_ba_author FOREIGN KEY (AuthorID) REFERENCES tblAuthor(AuthorID)
);

-- Customer Table
CREATE TABLE tblCustomer (
    CustomerID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    CustomerName VARCHAR2(100) NOT NULL,
    CustomerAdress VARCHAR2(200),
    CustomerEmail VARCHAR2(100)
);

-- Order Table
CREATE TABLE tblOrder (
    OrderID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER NOT NULL,
    OrderDate DATE NOT NULL,
    OrderTime VARCHAR2(10),  -- Could also be DATE or TIMESTAMP
    CONSTRAINT fk_order_customer FOREIGN KEY (CustomerID) REFERENCES tblCustomer(CustomerID)
);

-- OrderDetail Junction Table
CREATE TABLE tblOrderDetail (
    OrderDetailID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL,
    BookID NUMBER NOT NULL,
    OrderQuantity NUMBER NOT NULL,
    OrderPrice NUMBER(8,2),
    CONSTRAINT fk_od_order FOREIGN KEY (OrderID) REFERENCES tblOrder(OrderID),
    CONSTRAINT fk_od_book FOREIGN KEY (BookID) REFERENCES tblBook(BookID)
);
